
USE twitter_DB;


-- 1. 외래키 제약조건 먼저 삭제
ALTER TABLE REPLYCOMMENTLIKE 
DROP FOREIGN KEY fk_REPLYCOMMENTLIKE_REPLYCOMMENT1;

-- 2. 테이블 삭제
DROP TABLE IF EXISTS REPLY_COMMENT;

-- 3. 테이블 재생성
CREATE TABLE REPLY_COMMENT (
  POSTCOMMENT_SEQ_POST INT NOT NULL,
  RECOMMENT_SEQ INT NOT NULL AUTO_INCREMENT,
  USER_idUSER VARCHAR(20) NOT NULL,
  DETAIL VARCHAR(45) NOT NULL,
  DATE TIMESTAMP NULL,
  PRIMARY KEY (RECOMMENT_SEQ),
  INDEX fk_REPLYCOMMENT_POSTCOMMENT1_idx (POSTCOMMENT_SEQ_POST ASC),
  INDEX fk_REPLYCOMMENT_USER_idx (USER_idUSER ASC),
  CONSTRAINT fk_REPLYCOMMENT_POSTCOMMENT1
    FOREIGN KEY (POSTCOMMENT_SEQ_POST)
    REFERENCES POST_COMMENT (SEQ_POST)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_REPLYCOMMENT_USER
    FOREIGN KEY (USER_idUSER)
    REFERENCES USER (idUSER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- 4. 외래키 제약조건 다시 생성
ALTER TABLE REPLYCOMMENTLIKE 
ADD CONSTRAINT fk_REPLYCOMMENTLIKE_REPLYCOMMENT1
    FOREIGN KEY (REPLYCOMMENT_RECOMMENT_SEQ)
    REFERENCES REPLY_COMMENT (RECOMMENT_SEQ)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

-- 5. 완료 확인
DESC REPLY_COMMENT;
